/**
 * Config Templates — parameterised template strings for generated .claude/ files
 *
 * Each template function takes a typed params object and returns a file content
 * string. The config-generator.ts composes these into a GeneratedConfig.
 *
 * Design: pure template functions — no side effects, no I/O.
 */

import type {
	RegistryAgent,
	RegistrySkill,
	RegistryTeam,
} from "@/lib/registry/types";

// ============================================================================
// AGENT FRONTMATTER + BODY
// ============================================================================

export interface AgentTemplateParams {
	agentId: string;
	name: string;
	role: string;
	description: string;
	teamName: string;
	teamId: string;
	skills: RegistrySkill[];
	persona?: string;
}

/**
 * Generates a .claude/agents/<agentId>.md file.
 * Format mirrors the existing VantageStarter agent files (e.g. dev-frontend.md).
 */
export function agentTemplate(params: AgentTemplateParams): string {
	const skillList =
		params.skills.length > 0
			? params.skills
					.map((s) => `- **${s.name}** (${s.category}): ${s.description}`)
					.join("\n")
			: "- No skills defined for this agent.";

	const persona = params.persona
		? `\n## PERSONA\n\n${params.persona}\n`
		: `\n## PERSONA\n\n${params.name} — ${params.role} on the ${params.teamName}. ${params.description}\n`;

	return `---
name: ${params.agentId}
description: ${params.description}
tools: Read, Write, Edit, Bash, Grep, Glob
model: sonnet
memory: project
---
${persona}
## ROLE

You are the **${params.role}** for the **${params.teamName}** (team: \`${params.teamId}\`).

${params.description}

## SKILLS

${skillList}

## EXECUTION RULES

1. **Read first, Edit second.** Always read the target file before modifying. Use Edit for surgical changes.
2. **Stay in scope.** Only perform tasks that match your role. Route other requests to the appropriate specialist.
3. **Quality gate.** Before reporting done: zero TypeScript errors, zero linting errors.

## DEFINITION OF DONE

Before reporting done:
1. Task matches the ${params.role} scope for ${params.teamName}
2. Output is complete and actionable — no placeholders or TODOs
3. Any code changes: \`npx @biomejs/biome check --no-errors-on-unmatched <files>\` — zero errors

## RETURN FORMAT

Action taken + result + any follow-up needed. Max 200 tokens.
`;
}

// ============================================================================
// CLAUDE.MD
// ============================================================================

export interface ClaudeMdTemplateParams {
	projectName: string;
	clientName: string;
	sector: string;
	summary: string;
	painPoints: string[];
	teams: Array<{
		team: RegistryTeam;
		agents: RegistryAgent[];
		skills: RegistrySkill[];
	}>;
	generatedAt: string;
}

/**
 * Generates the CLAUDE.md project bible for the client's .claude/ setup.
 * Includes project context, agent routing table, and stack section.
 */
export function claudeMdTemplate(params: ClaudeMdTemplateParams): string {
	const routingRows = params.teams
		.flatMap(({ agents }) => agents)
		.map((a) => `| ${a.name} tasks | \`${a.id}\` |`)
		.join("\n");

	const teamSections = params.teams
		.map(({ team, agents, skills }) => {
			const agentList = agents
				.map((a) => `  - \`${a.id}\` — ${a.name} (${a.role})`)
				.join("\n");
			const skillList = skills
				.map((s) => `  - **${s.name}**: ${s.description}`)
				.join("\n");
			return `### ${team.name} (\`${team.id}\`)

${team.description}

**Agents:**
${agentList}

**Skills:**
${skillList}`;
		})
		.join("\n\n");

	const painList =
		params.painPoints.length > 0
			? params.painPoints.map((p) => `- ${p}`).join("\n")
			: "- (none specified)";

	return `# ${params.projectName} — Claude Code Project Bible

**Client:** ${params.clientName}
**Sector:** ${params.sector}
**Generated:** ${params.generatedAt}
**Generated by:** VantageStarter Consultant Onboarding

---

## Project Summary

${params.summary}

## Business Pain Points

${painList}

---

## ORCHESTRATION PROTOCOL

You are the orchestrator. You do NOT write work product yourself. You delegate to specialist agents.

### Rules

1. **Diagnose before delegating.** Read the code or context. Find the exact file, section, and change needed.
2. **One task per agent.** One file, one section, one deliverable.
3. **Background only.** Always \`run_in_background: true\`. Foreground blocks the user.
4. **Do only what is asked.** No extra work. No assumptions.

### Agent Routing

| Task | Agent |
|------|-------|
${routingRows}

---

## ACTIVE TEAMS

${teamSections}

---

## STACK

This project uses the following AI agent teams configured via VantageStarter:

| Team | Category | Purpose |
|------|----------|---------|
${params.teams.map(({ team }) => `| ${team.name} | ${team.category} | ${team.description} |`).join("\n")}

---

## CONVENTIONS

- **Agents are specialists.** Route tasks to the correct agent. Don't do everything yourself.
- **Scope matters.** Each agent has a defined role — don't ask them to do work outside it.
- **Quality gate.** All deliverables must be complete and actionable before reporting done.
`;
}

// ============================================================================
// SESSION START HOOK
// ============================================================================

export interface SessionStartTemplateParams {
	projectName: string;
	clientName: string;
	sector: string;
	agentIds: string[];
}

/**
 * Generates a customised hooks/session-start.py for the client project.
 * Prints project context and active agents on every session start.
 */
export function sessionStartTemplate(
	params: SessionStartTemplateParams,
): string {
	const agentList = params.agentIds.map((id) => `    - ${id}`).join("\n");

	return `#!/usr/bin/env python3
"""
Session Start Hook — ${params.projectName}

Prints project context and active agents on every Claude Code session start.
Generated by VantageStarter Consultant Onboarding.
"""

import json
import sys

def main():
    try:
        hook_input = json.loads(sys.stdin.read())
    except (json.JSONDecodeError, ValueError):
        hook_input = {}

    context_lines = [
        "=" * 60,
        f"Project: ${params.projectName}",
        f"Client:  ${params.clientName}",
        f"Sector:  ${params.sector}",
        "",
        "Active agents:",
${agentList.replace(/^/gm, "        ").trim() || '        "    (none)"'},
        "=" * 60,
        "",
        "ORCHESTRATION REMINDER:",
        "- Delegate to specialist agents. Do not write work product yourself.",
        "- Read CLAUDE.md before every session for routing rules.",
        "=" * 60,
    ]

    for line in context_lines:
        print(line, file=sys.stderr)

    # Pass through — do not block
    print(json.dumps(hook_input))

if __name__ == "__main__":
    main()
`;
}

// ============================================================================
// SKILLS MANIFEST
// ============================================================================

export interface SkillsManifestTemplateParams {
	skills: RegistrySkill[];
	projectName: string;
}

/**
 * Generates a .claude/skills/SKILLS.md manifest listing all active skills.
 * This is a reference document — full skill SKILL.md files are not generated
 * (they live in the vantage-registry and are fetched on demand).
 */
export function skillsManifestTemplate(
	params: SkillsManifestTemplateParams,
): string {
	const byCategory = params.skills.reduce<Record<string, RegistrySkill[]>>(
		(acc, skill) => {
			const cat = skill.category;
			if (!acc[cat]) acc[cat] = [];
			acc[cat].push(skill);
			return acc;
		},
		{},
	);

	const categoryBlocks = Object.entries(byCategory)
		.sort(([a], [b]) => a.localeCompare(b))
		.map(([category, skills]) => {
			const rows = skills
				.map((s) => `| \`${s.id}\` | ${s.name} | ${s.description} |`)
				.join("\n");
			return `### ${category.charAt(0).toUpperCase() + category.slice(1)}\n\n| ID | Name | Description |\n|----|------|-------------|\n${rows}`;
		})
		.join("\n\n");

	return `# Active Skills — ${params.projectName}

This manifest lists all skills activated for this project via VantageStarter Consultant Onboarding.

Agents should load individual skill files from the vantage-registry when executing tasks.

---

## Skills by Category

${categoryBlocks}

---

Total: **${params.skills.length} skills** across **${Object.keys(byCategory).length} categories**.
`;
}
